package view;

import java.util.ArrayList;

import javax.swing.table.TableColumnModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chizhang
 */
public class HomePage extends javax.swing.JFrame {

	private int courseID;
	//private CourseworkSummaryController courseworkSummaryController;
    /**
     * Creates new form home Page
     */
    public HomePage() {
        initComponents();
    }
    
    /**
     * Create new form home page with a specific course id
     * TODO: link to the given course
     * @param courseID
     */
    public HomePage(int courseID) {
    	this.courseID = courseID;
    	//this.courseworkSummaryController = new CourseworkSummaryController(courseID);
    	initComponents();
    }
    
    public int getCourseID() {
    	return this.courseID;
    }
    
//    public CourseworkSummaryController getCourseworkSummaryController() {
//    	return this.courseworkSummaryController;
//    }
//    
    /**
     * 
     * TODO: get all category names
     * @return 
     */
    private ArrayList<String> getAllCategories() {
    	return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        couseNameLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        backToCourseSelectBt = new javax.swing.JButton();
        mainPanel2 = new javax.swing.JPanel();
        moreActionLabel = new javax.swing.JLabel();
        moreActionsPanel = new javax.swing.JPanel();
        studentInfoBt = new javax.swing.JButton();
        createCourseworkBt = new javax.swing.JButton();
        courseLogisticBt3 = new javax.swing.JButton();
        courseRubricBt4 = new javax.swing.JButton();
        addNoteBt = new javax.swing.JButton();
        exportCSVBt = new javax.swing.JButton();
        summaryLabel1 = new javax.swing.JLabel();
        mainTableScrollPane = new javax.swing.JScrollPane();
        mainSummaryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(770, 496));

        headerPanel.setBackground(new java.awt.Color(25, 118, 210));

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Dashboard");

        /**
         * TODO: get course name for this course
         */
        //this.courseworkSummaryController.getDashboardInfo(courseID);
        couseNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        couseNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        couseNameLabel.setText("Course Name");

        
        /**
         * TODO: get course semester for this course
         */
        semesterLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        semesterLabel.setForeground(new java.awt.Color(255, 255, 255));
        semesterLabel.setText("Semester");

        backToCourseSelectBt.setBackground(new java.awt.Color(255, 255, 255));
        backToCourseSelectBt.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backToCourseSelectBt.setForeground(new java.awt.Color(25, 118, 210));
        backToCourseSelectBt.setText("Back");
        backToCourseSelectBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCourseSelectBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(semesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(couseNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToCourseSelectBt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToCourseSelectBt)
                .addGap(18, 18, 18))
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(semesterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(couseNameLabel))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mainPanel2.setBackground(new java.awt.Color(255, 252, 252));
        mainPanel2.setPreferredSize(new java.awt.Dimension(770, 496));

        moreActionLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        moreActionLabel.setForeground(new java.awt.Color(25, 118, 210));
        moreActionLabel.setText("More Actions");

        studentInfoBt.setBackground(new java.awt.Color(255, 255, 255));
        studentInfoBt.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        studentInfoBt.setForeground(new java.awt.Color(25, 118, 210));
        studentInfoBt.setText("Student Info");
        studentInfoBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoBtActionPerformed(evt);
            }
        });

        createCourseworkBt.setBackground(new java.awt.Color(255, 255, 255));
        createCourseworkBt.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        createCourseworkBt.setForeground(new java.awt.Color(25, 118, 210));
        createCourseworkBt.setText("Create Coursework");
        createCourseworkBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCourseworkBtActionPerformed(evt);
            }
        });

        courseLogisticBt3.setBackground(new java.awt.Color(255, 255, 255));
        courseLogisticBt3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        courseLogisticBt3.setForeground(new java.awt.Color(25, 118, 210));
        courseLogisticBt3.setText("Course Logistic");
        courseLogisticBt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseLogisticBt3ActionPerformed(evt);
            }
        });

        courseRubricBt4.setBackground(new java.awt.Color(255, 255, 255));
        courseRubricBt4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        courseRubricBt4.setForeground(new java.awt.Color(25, 118, 210));
        courseRubricBt4.setText("Course Rubric");
        courseRubricBt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseRubricBt4ActionPerformed(evt);
            }
        });

        addNoteBt.setBackground(new java.awt.Color(255, 255, 255));
        addNoteBt.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        addNoteBt.setForeground(new java.awt.Color(25, 118, 210));
        addNoteBt.setText("Add Note (Optional)");
        addNoteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteBtActionPerformed(evt);
            }
        });

        exportCSVBt.setBackground(new java.awt.Color(255, 255, 255));
        exportCSVBt.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        exportCSVBt.setForeground(new java.awt.Color(25, 118, 210));
        exportCSVBt.setText("Export CSV");
        exportCSVBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportCSVBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moreActionsPanelLayout = new javax.swing.GroupLayout(moreActionsPanel);
        moreActionsPanel.setLayout(moreActionsPanelLayout);
        moreActionsPanelLayout.setHorizontalGroup(
            moreActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moreActionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moreActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentInfoBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createCourseworkBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseLogisticBt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseRubricBt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addNoteBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exportCSVBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        moreActionsPanelLayout.setVerticalGroup(
            moreActionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moreActionsPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(studentInfoBt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createCourseworkBt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseLogisticBt3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseRubricBt4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNoteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportCSVBt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        summaryLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        summaryLabel1.setForeground(new java.awt.Color(25, 118, 210));
        summaryLabel1.setText("Course work summay  ");

        mainTableScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        mainTableScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        mainSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 13"
            }
        ));
        // set rows height
        mainSummaryTable.setRowHeight(30);
        // set column width
        TableColumnModel columnModel = mainSummaryTable.getColumnModel();
        int cols = mainSummaryTable.getColumnCount();
        
        mainSummaryTable.setColumnSelectionAllowed(true);
        mainSummaryTable.getTableHeader().setReorderingAllowed(false);
        mainTableScrollPane.setViewportView(mainSummaryTable);
        mainSummaryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (mainSummaryTable.getColumnModel().getColumnCount() > 0) {
            mainSummaryTable.getColumnModel().getColumn(0).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(1).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(2).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(3).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(4).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(5).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(6).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(7).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(8).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(9).setResizable(false);
            mainSummaryTable.getColumnModel().getColumn(9).setPreferredWidth(70);
        }
        for(int i = 0;i<cols;i++){
            columnModel.getColumn(i).setPreferredWidth(80);
        }
        mainSummaryTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);


        javax.swing.GroupLayout mainPanel2Layout = new javax.swing.GroupLayout(mainPanel2);
        mainPanel2.setLayout(mainPanel2Layout);
        mainPanel2Layout.setHorizontalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel2Layout.createSequentialGroup()
                        .addComponent(summaryLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanel2Layout.createSequentialGroup()
                        .addComponent(mainTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                        .addGap(36, 36, 36)))
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moreActionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moreActionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        mainPanel2Layout.setVerticalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moreActionLabel)
                    .addComponent(summaryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moreActionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToCourseSelectBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCourseSelectBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToCourseSelectBtActionPerformed

    private void exportCSVBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportCSVBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportCSVBtActionPerformed

    private void addNoteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNoteBtActionPerformed

    private void courseRubricBt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseRubricBt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseRubricBt4ActionPerformed

    private void courseLogisticBt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseLogisticBt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseLogisticBt3ActionPerformed

    private void createCourseworkBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCourseworkBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCourseworkBtActionPerformed

    private void studentInfoBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentInfoBtActionPerformed
        // TODO connect to the student info page:
        
    }//GEN-LAST:event_studentInfoBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNoteBt;
    private javax.swing.JButton backToCourseSelectBt;
    private javax.swing.JButton courseLogisticBt3;
    private javax.swing.JButton courseRubricBt4;
    private javax.swing.JLabel couseNameLabel;
    private javax.swing.JButton createCourseworkBt;
    private javax.swing.JButton exportCSVBt;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel mainPanel2;
    private javax.swing.JTable mainSummaryTable;
    private javax.swing.JScrollPane mainTableScrollPane;
    private javax.swing.JLabel moreActionLabel;
    private javax.swing.JPanel moreActionsPanel;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JButton studentInfoBt;
    private javax.swing.JLabel summaryLabel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
